// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: department.sql

package sqlcdb

import (
	"context"
)

const addDepartment = `-- name: AddDepartment :execrows
INSERT INTO departments (department_name)
	VALUES ($1)
`

func (q *Queries) AddDepartment(ctx context.Context, departmentName string) (int64, error) {
	result, err := q.db.ExecContext(ctx, addDepartment, departmentName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDepartment = `-- name: DeleteDepartment :execrows
DELETE FROM departments WHERE department_id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, departmentID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDepartment, departmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDepartment = `-- name: GetDepartment :one
SELECT  d.department_id,
        d.department_name,
        CAST((SELECT COALESCE(COUNT(i.id), 0) FROM inventory AS i WHERE d.department_id = i.department_id) AS INTEGER) AS total_items
	FROM departments AS d
	WHERE d.department_id = $1 AND d.department_id != 1
`

type GetDepartmentRow struct {
	DepartmentID   int32  `json:"department_id"`
	DepartmentName string `json:"department_name"`
	TotalItems     int32  `json:"total_items"`
}

func (q *Queries) GetDepartment(ctx context.Context, departmentID int32) (GetDepartmentRow, error) {
	row := q.db.QueryRowContext(ctx, getDepartment, departmentID)
	var i GetDepartmentRow
	err := row.Scan(&i.DepartmentID, &i.DepartmentName, &i.TotalItems)
	return i, err
}

const getDepartments = `-- name: GetDepartments :many
SELECT  d.department_id,
        d.department_name,
        CAST((SELECT COALESCE(COUNT(i.id), 0)
	FROM inventory AS i
	WHERE d.department_id = i.department_id) AS INTEGER) AS total_items
	FROM departments AS d
	WHERE department_id != 1
	ORDER BY department_id DESC
`

type GetDepartmentsRow struct {
	DepartmentID   int32  `json:"department_id"`
	DepartmentName string `json:"department_name"`
	TotalItems     int32  `json:"total_items"`
}

func (q *Queries) GetDepartments(ctx context.Context) ([]GetDepartmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDepartmentsRow
	for rows.Next() {
		var i GetDepartmentsRow
		if err := rows.Scan(&i.DepartmentID, &i.DepartmentName, &i.TotalItems); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :execrows
UPDATE departments
    SET department_name = $1
	WHERE department_id = $2
`

type UpdateDepartmentParams struct {
	DepartmentName string `json:"department_name"`
	DepartmentID   int32  `json:"department_id"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDepartment, arg.DepartmentName, arg.DepartmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
