// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const addEntryToInvoice = `-- name: AddEntryToInvoice :execrows
INSERT INTO invoice_data (
	invoice_id,
	rawtext,
	upc,
	details,
	qty,
	item_cost,
	total_cost,
	discount_cost,
	true_cost
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type AddEntryToInvoiceParams struct {
	InvoiceID    int32   `json:"invoice_id"`
	Rawtext      string  `json:"rawtext"`
	Upc          string  `json:"upc"`
	Details      string  `json:"details"`
	Qty          int32   `json:"qty"`
	ItemCost     float64 `json:"item_cost"`
	TotalCost    float64 `json:"total_cost"`
	DiscountCost float64 `json:"discount_cost"`
	TrueCost     float64 `json:"true_cost"`
}

func (q *Queries) AddEntryToInvoice(ctx context.Context, arg AddEntryToInvoiceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addEntryToInvoice,
		arg.InvoiceID,
		arg.Rawtext,
		arg.Upc,
		arg.Details,
		arg.Qty,
		arg.ItemCost,
		arg.TotalCost,
		arg.DiscountCost,
		arg.TrueCost,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const addInvoice = `-- name: AddInvoice :execrows
INSERT INTO invoices (invoice_name, invoice_type, department_id)
	VALUES ($1, $2, $3)
`

type AddInvoiceParams struct {
	InvoiceName  string `json:"invoice_name"`
	InvoiceType  string `json:"invoice_type"`
	DepartmentID int32  `json:"department_id"`
}

func (q *Queries) AddInvoice(ctx context.Context, arg AddInvoiceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addInvoice, arg.InvoiceName, arg.InvoiceType, arg.DepartmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countAllInvoiceEntrys = `-- name: CountAllInvoiceEntrys :one
SELECT COUNT(invoice_data_id)
FROM invoice_data
WHERE invoice_id = $1
`

func (q *Queries) CountAllInvoiceEntrys(ctx context.Context, invoiceID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllInvoiceEntrys, invoiceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEntryFromInvoice = `-- name: DeleteEntryFromInvoice :execrows
DELETE FROM invoice_data WHERE invoice_data_id = $1
`

func (q *Queries) DeleteEntryFromInvoice(ctx context.Context, invoiceDataID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEntryFromInvoice, invoiceDataID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteInvoice = `-- name: DeleteInvoice :execrows
DELETE FROM invoices WHERE invoice_id = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, invoiceID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInvoice, invoiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteInvoiceData = `-- name: DeleteInvoiceData :execrows
DELETE FROM invoice_data WHERE invoice_id = $1
`

func (q *Queries) DeleteInvoiceData(ctx context.Context, invoiceID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInvoiceData, invoiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getInvoiceById = `-- name: GetInvoiceById :one
SELECT
	v.invoice_id,
	v.invoice_name,
	v.invoice_type,
	v.department_id,
	d.department_name,
	COALESCE(COUNT(vd.qty), 0)::bigint AS total_count,
	v.created_at
FROM invoices v
LEFT JOIN invoice_data vd ON v.invoice_id = vd.invoice_id
JOIN departments d ON v.department_id = d.department_id
WHERE v.invoice_id = $1
GROUP BY v.invoice_id, v.invoice_name, v.invoice_type, v.department_id, d.department_name, v.created_at
`

type GetInvoiceByIdRow struct {
	InvoiceID      int32     `json:"invoice_id"`
	InvoiceName    string    `json:"invoice_name"`
	InvoiceType    string    `json:"invoice_type"`
	DepartmentID   int32     `json:"department_id"`
	DepartmentName string    `json:"department_name"`
	TotalCount     int64     `json:"total_count"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) GetInvoiceById(ctx context.Context, invoiceID int32) (GetInvoiceByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceById, invoiceID)
	var i GetInvoiceByIdRow
	err := row.Scan(
		&i.InvoiceID,
		&i.InvoiceName,
		&i.InvoiceType,
		&i.DepartmentID,
		&i.DepartmentName,
		&i.TotalCount,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceEntryById = `-- name: GetInvoiceEntryById :one
SELECT
	id.invoice_data_id,
	id.invoice_id,
	id.rawtext,
	id.upc,
	id.details,
	id.qty,
	id.item_cost,
	id.total_cost,
	id.discount_cost,
	id.true_cost
FROM invoice_data id
WHERE id.invoice_data_id = $1
`

func (q *Queries) GetInvoiceEntryById(ctx context.Context, invoiceDataID int32) (InvoiceDatum, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceEntryById, invoiceDataID)
	var i InvoiceDatum
	err := row.Scan(
		&i.InvoiceDataID,
		&i.InvoiceID,
		&i.Rawtext,
		&i.Upc,
		&i.Details,
		&i.Qty,
		&i.ItemCost,
		&i.TotalCost,
		&i.DiscountCost,
		&i.TrueCost,
	)
	return i, err
}

const getInvoiceEntrys = `-- name: GetInvoiceEntrys :many
SELECT
	id.invoice_data_id,
	id.invoice_id,
	id.rawtext,
	id.upc,
	id.details,
	id.qty,
	id.item_cost,
	id.total_cost,
	id.discount_cost,
	id.true_cost,
	COUNT(*) OVER() AS total_items
FROM invoice_data id
WHERE id.invoice_id = $1
ORDER BY id.qty DESC
LIMIT $2 OFFSET $3
`

type GetInvoiceEntrysParams struct {
	InvoiceID int32 `json:"invoice_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type GetInvoiceEntrysRow struct {
	InvoiceDataID int32   `json:"invoice_data_id"`
	InvoiceID     int32   `json:"invoice_id"`
	Rawtext       string  `json:"rawtext"`
	Upc           string  `json:"upc"`
	Details       string  `json:"details"`
	Qty           int32   `json:"qty"`
	ItemCost      float64 `json:"item_cost"`
	TotalCost     float64 `json:"total_cost"`
	DiscountCost  float64 `json:"discount_cost"`
	TrueCost      float64 `json:"true_cost"`
	TotalItems    int64   `json:"total_items"`
}

func (q *Queries) GetInvoiceEntrys(ctx context.Context, arg GetInvoiceEntrysParams) ([]GetInvoiceEntrysRow, error) {
	rows, err := q.db.QueryContext(ctx, getInvoiceEntrys, arg.InvoiceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInvoiceEntrysRow
	for rows.Next() {
		var i GetInvoiceEntrysRow
		if err := rows.Scan(
			&i.InvoiceDataID,
			&i.InvoiceID,
			&i.Rawtext,
			&i.Upc,
			&i.Details,
			&i.Qty,
			&i.ItemCost,
			&i.TotalCost,
			&i.DiscountCost,
			&i.TrueCost,
			&i.TotalItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvoices = `-- name: GetInvoices :many
SELECT
	v.invoice_id,
	v.invoice_name,
	v.invoice_type,
	v.department_id,
	d.department_name,
	COALESCE(COUNT(vd.qty), 0)::bigint AS total_count,
	v.created_at
FROM invoices v
LEFT JOIN invoice_data vd ON v.invoice_id = vd.invoice_id
LEFT JOIN departments d ON v.department_id = d.department_id
WHERE ($1::integer = 0 OR v.department_id = $1)
GROUP BY v.invoice_id, v.invoice_name, v.invoice_type, v.department_id, d.department_name, v.created_at
ORDER BY v.invoice_id DESC
`

type GetInvoicesRow struct {
	InvoiceID      int32          `json:"invoice_id"`
	InvoiceName    string         `json:"invoice_name"`
	InvoiceType    string         `json:"invoice_type"`
	DepartmentID   int32          `json:"department_id"`
	DepartmentName sql.NullString `json:"department_name"`
	TotalCount     int64          `json:"total_count"`
	CreatedAt      time.Time      `json:"created_at"`
}

func (q *Queries) GetInvoices(ctx context.Context, departmentID int32) ([]GetInvoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, getInvoices, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInvoicesRow
	for rows.Next() {
		var i GetInvoicesRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.InvoiceName,
			&i.InvoiceType,
			&i.DepartmentID,
			&i.DepartmentName,
			&i.TotalCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntryInInvoice = `-- name: UpdateEntryInInvoice :execrows
UPDATE invoice_data
	SET
		rawtext = $1,
		upc = $2,
		details = $3,
		qty = $4,
		item_cost = $5,
		total_cost = $6,
		discount_cost = $7,
		true_cost = $8
	WHERE invoice_data_id = $9
`

type UpdateEntryInInvoiceParams struct {
	Rawtext       string  `json:"rawtext"`
	Upc           string  `json:"upc"`
	Details       string  `json:"details"`
	Qty           int32   `json:"qty"`
	ItemCost      float64 `json:"item_cost"`
	TotalCost     float64 `json:"total_cost"`
	DiscountCost  float64 `json:"discount_cost"`
	TrueCost      float64 `json:"true_cost"`
	InvoiceDataID int32   `json:"invoice_data_id"`
}

func (q *Queries) UpdateEntryInInvoice(ctx context.Context, arg UpdateEntryInInvoiceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEntryInInvoice,
		arg.Rawtext,
		arg.Upc,
		arg.Details,
		arg.Qty,
		arg.ItemCost,
		arg.TotalCost,
		arg.DiscountCost,
		arg.TrueCost,
		arg.InvoiceDataID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateInvoice = `-- name: UpdateInvoice :execrows
UPDATE invoices
	SET invoice_name = $1
	WHERE invoice_id = $2
`

type UpdateInvoiceParams struct {
	InvoiceName string `json:"invoice_name"`
	InvoiceID   int32  `json:"invoice_id"`
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateInvoice, arg.InvoiceName, arg.InvoiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
