// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const addItem = `-- name: AddItem :execrows
INSERT INTO inventory (vendor_id, location_id, department_id, upc, invoice_number, name, brand, description, price, weighed, count)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type AddItemParams struct {
	VendorID      sql.NullInt32 `json:"vendor_id"`
	LocationID    sql.NullInt32 `json:"location_id"`
	DepartmentID  int32         `json:"department_id"`
	Upc           string        `json:"upc"`
	InvoiceNumber string        `json:"invoice_number"`
	Name          string        `json:"name"`
	Brand         string        `json:"brand"`
	Description   string        `json:"description"`
	Price         float64       `json:"price"`
	Weighed       bool          `json:"weighed"`
	Count         int32         `json:"count"`
}

func (q *Queries) AddItem(ctx context.Context, arg AddItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addItem,
		arg.VendorID,
		arg.LocationID,
		arg.DepartmentID,
		arg.Upc,
		arg.InvoiceNumber,
		arg.Name,
		arg.Brand,
		arg.Description,
		arg.Price,
		arg.Weighed,
		arg.Count,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countAllItems = `-- name: CountAllItems :one
SELECT COUNT(id)
FROM inventory
WHERE ($1::boolean = true OR deleted = false)
`

func (q *Queries) CountAllItems(ctx context.Context, countDeleted bool) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllItems, countDeleted)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteItem = `-- name: DeleteItem :execrows
UPDATE inventory
	SET deleted = true, soldout_at = CURRENT_TIMESTAMP
	WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteItemPermanent = `-- name: DeleteItemPermanent :execrows
DELETE FROM inventory WHERE id = $1
`

func (q *Queries) DeleteItemPermanent(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteItemPermanent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllItems = `-- name: GetAllItems :many
SELECT
	i.id,
	v.vendor_id,
	v.vendor_name,
	l.location_id,
	l.location_name,
	i.department_id,
	d.department_name,
	i.upc,
	i.invoice_number,
	i.brand,
	i.name,
	i.description,
	i.price,
	i.weighed,
	COALESCE(i.count, 0) AS count,
	i.deleted,
	i.arrived_at,
	i.soldout_at,
	COUNT(*) OVER() AS entry_count
FROM inventory i
JOIN vendors v ON i.vendor_id = v.vendor_id
JOIN locations l ON i.location_id = l.location_id
JOIN departments d ON i.department_id = d.department_id
LEFT JOIN list_data ld ON i.id = ld.item_id AND ld.list_id = $1
WHERE ($2::boolean = true OR i.deleted = false)
	AND ($3::integer = 0 OR i.vendor_id = $3)
	AND ($4::integer = 0 OR i.location_id = $4)
	AND ($5::integer = 0 OR i.department_id = $5)
	AND ($1 = 0 OR ld.list_id = $1)
ORDER BY CASE $6::text
	WHEN 'date' THEN CAST(i.arrived_at AS TEXT)
	WHEN 'name' THEN i.name
	ELSE i.upc
END DESC
LIMIT $8 OFFSET $7
`

type GetAllItemsParams struct {
	ListID      int32  `json:"list_id"`
	ShowDeleted bool   `json:"show_deleted"`
	Vendor      int32  `json:"vendor"`
	Location    int32  `json:"location"`
	Department  int32  `json:"department"`
	OrderBy     string `json:"order_by"`
	PageOffset  int32  `json:"page_offset"`
	PageSize    int32  `json:"page_size"`
}

type GetAllItemsRow struct {
	ID             int32        `json:"id"`
	VendorID       int32        `json:"vendor_id"`
	VendorName     string       `json:"vendor_name"`
	LocationID     int32        `json:"location_id"`
	LocationName   string       `json:"location_name"`
	DepartmentID   int32        `json:"department_id"`
	DepartmentName string       `json:"department_name"`
	Upc            string       `json:"upc"`
	InvoiceNumber  string       `json:"invoice_number"`
	Brand          string       `json:"brand"`
	Name           string       `json:"name"`
	Description    string       `json:"description"`
	Price          float64      `json:"price"`
	Weighed        bool         `json:"weighed"`
	Count          int32        `json:"count"`
	Deleted        sql.NullBool `json:"deleted"`
	ArrivedAt      time.Time    `json:"arrived_at"`
	SoldoutAt      *time.Time   `json:"soldout_at"`
	EntryCount     int64        `json:"entry_count"`
}

func (q *Queries) GetAllItems(ctx context.Context, arg GetAllItemsParams) ([]GetAllItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllItems,
		arg.ListID,
		arg.ShowDeleted,
		arg.Vendor,
		arg.Location,
		arg.Department,
		arg.OrderBy,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllItemsRow
	for rows.Next() {
		var i GetAllItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.VendorName,
			&i.LocationID,
			&i.LocationName,
			&i.DepartmentID,
			&i.DepartmentName,
			&i.Upc,
			&i.InvoiceNumber,
			&i.Brand,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Weighed,
			&i.Count,
			&i.Deleted,
			&i.ArrivedAt,
			&i.SoldoutAt,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemById = `-- name: GetItemById :one
SELECT
	i.id,
	v.vendor_id,
	v.vendor_name,
	l.location_id,
	l.location_name,
	i.department_id,
	d.department_name,
	i.upc,
	i.invoice_number,
	i.brand,
	i.name,
	i.description,
	i.price,
	i.weighed,
	COALESCE(i.count, 0) AS count,
	i.deleted,
	i.arrived_at,
	i.soldout_at
FROM inventory i
JOIN vendors v ON i.vendor_id = v.vendor_id
JOIN locations l ON i.location_id = l.location_id
JOIN departments d ON i.department_id = d.department_id
WHERE i.id = $1
`

type GetItemByIdRow struct {
	ID             int32        `json:"id"`
	VendorID       int32        `json:"vendor_id"`
	VendorName     string       `json:"vendor_name"`
	LocationID     int32        `json:"location_id"`
	LocationName   string       `json:"location_name"`
	DepartmentID   int32        `json:"department_id"`
	DepartmentName string       `json:"department_name"`
	Upc            string       `json:"upc"`
	InvoiceNumber  string       `json:"invoice_number"`
	Brand          string       `json:"brand"`
	Name           string       `json:"name"`
	Description    string       `json:"description"`
	Price          float64      `json:"price"`
	Weighed        bool         `json:"weighed"`
	Count          int32        `json:"count"`
	Deleted        sql.NullBool `json:"deleted"`
	ArrivedAt      time.Time    `json:"arrived_at"`
	SoldoutAt      *time.Time   `json:"soldout_at"`
}

func (q *Queries) GetItemById(ctx context.Context, id int32) (GetItemByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getItemById, id)
	var i GetItemByIdRow
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.VendorName,
		&i.LocationID,
		&i.LocationName,
		&i.DepartmentID,
		&i.DepartmentName,
		&i.Upc,
		&i.InvoiceNumber,
		&i.Brand,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Weighed,
		&i.Count,
		&i.Deleted,
		&i.ArrivedAt,
		&i.SoldoutAt,
	)
	return i, err
}

const restoreItem = `-- name: RestoreItem :execrows
UPDATE inventory
	SET deleted = false, soldout_at = NULL
	WHERE id = $1
`

func (q *Queries) RestoreItem(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateItem = `-- name: UpdateItem :execrows
UPDATE inventory
	SET department_id = $1, vendor_id = $2, location_id = $3, upc = $4, invoice_number = $5, brand = $6, name = $7, description = $8, price = $9, weighed = $10, count = $11, deleted = $12, arrived_at = $13, soldout_at = $14
	WHERE id = $15
`

type UpdateItemParams struct {
	DepartmentID  int32         `json:"department_id"`
	VendorID      sql.NullInt32 `json:"vendor_id"`
	LocationID    sql.NullInt32 `json:"location_id"`
	Upc           string        `json:"upc"`
	InvoiceNumber string        `json:"invoice_number"`
	Brand         string        `json:"brand"`
	Name          string        `json:"name"`
	Description   string        `json:"description"`
	Price         float64       `json:"price"`
	Weighed       bool          `json:"weighed"`
	Count         int32         `json:"count"`
	Deleted       sql.NullBool  `json:"deleted"`
	ArrivedAt     time.Time     `json:"arrived_at"`
	SoldoutAt     *time.Time    `json:"soldout_at"`
	ID            int32         `json:"id"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateItem,
		arg.DepartmentID,
		arg.VendorID,
		arg.LocationID,
		arg.Upc,
		arg.InvoiceNumber,
		arg.Brand,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Weighed,
		arg.Count,
		arg.Deleted,
		arg.ArrivedAt,
		arg.SoldoutAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateItemDepartment = `-- name: UpdateItemDepartment :execrows
UPDATE inventory
	SET location_id = $1, department_id = $2
	WHERE id = $3
`

type UpdateItemDepartmentParams struct {
	LocationID   sql.NullInt32 `json:"location_id"`
	DepartmentID int32         `json:"department_id"`
	ID           int32         `json:"id"`
}

func (q *Queries) UpdateItemDepartment(ctx context.Context, arg UpdateItemDepartmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateItemDepartment, arg.LocationID, arg.DepartmentID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateItemNoDepartment = `-- name: UpdateItemNoDepartment :execrows
UPDATE inventory
	SET vendor_id = $1, location_id = $2, upc = $3, invoice_number = $4, brand = $5, name = $6, description = $7, price = $8, weighed = $9, count = $10, deleted = $11, arrived_at = $12, soldout_at = $13
	WHERE id = $14
`

type UpdateItemNoDepartmentParams struct {
	VendorID      sql.NullInt32 `json:"vendor_id"`
	LocationID    sql.NullInt32 `json:"location_id"`
	Upc           string        `json:"upc"`
	InvoiceNumber string        `json:"invoice_number"`
	Brand         string        `json:"brand"`
	Name          string        `json:"name"`
	Description   string        `json:"description"`
	Price         float64       `json:"price"`
	Weighed       bool          `json:"weighed"`
	Count         int32         `json:"count"`
	Deleted       sql.NullBool  `json:"deleted"`
	ArrivedAt     time.Time     `json:"arrived_at"`
	SoldoutAt     *time.Time    `json:"soldout_at"`
	ID            int32         `json:"id"`
}

func (q *Queries) UpdateItemNoDepartment(ctx context.Context, arg UpdateItemNoDepartmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateItemNoDepartment,
		arg.VendorID,
		arg.LocationID,
		arg.Upc,
		arg.InvoiceNumber,
		arg.Brand,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Weighed,
		arg.Count,
		arg.Deleted,
		arg.ArrivedAt,
		arg.SoldoutAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
