// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lists.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const addEntryToList = `-- name: AddEntryToList :one
INSERT INTO list_data (list_id, item_id, list_count)
	VALUES ($1, $2, 1)
	RETURNING list_entry_id
`

type AddEntryToListParams struct {
	ListID int32 `json:"list_id"`
	ItemID int32 `json:"item_id"`
}

func (q *Queries) AddEntryToList(ctx context.Context, arg AddEntryToListParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, addEntryToList, arg.ListID, arg.ItemID)
	var list_entry_id int32
	err := row.Scan(&list_entry_id)
	return list_entry_id, err
}

const addList = `-- name: AddList :execrows
INSERT INTO lists (list_name, department_id)
	VALUES ($1, $2)
`

type AddListParams struct {
	ListName     string `json:"list_name"`
	DepartmentID int32  `json:"department_id"`
}

func (q *Queries) AddList(ctx context.Context, arg AddListParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addList, arg.ListName, arg.DepartmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEntryFromList = `-- name: DeleteEntryFromList :execrows
DELETE FROM list_data WHERE list_entry_id = $1
`

func (q *Queries) DeleteEntryFromList(ctx context.Context, listEntryID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEntryFromList, listEntryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteList = `-- name: DeleteList :execrows
DELETE FROM lists WHERE list_id = $1
`

func (q *Queries) DeleteList(ctx context.Context, listID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteList, listID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getListById = `-- name: GetListById :one
SELECT
	l.list_id,
	l.list_name,
	l.department_id,
	d.department_name,
	COALESCE(COUNT(ld.list_count), 0)::bigint AS total_items,
	l.created_at
FROM lists l
JOIN departments d ON l.department_id = d.department_id
LEFT JOIN list_data ld ON l.list_id = ld.list_id
WHERE l.list_id = $1
GROUP BY l.list_id, l.list_name, l.department_id, d.department_name, l.created_at
`

type GetListByIdRow struct {
	ListID         int32     `json:"list_id"`
	ListName       string    `json:"list_name"`
	DepartmentID   int32     `json:"department_id"`
	DepartmentName string    `json:"department_name"`
	TotalItems     int64     `json:"total_items"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) GetListById(ctx context.Context, listID int32) (GetListByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getListById, listID)
	var i GetListByIdRow
	err := row.Scan(
		&i.ListID,
		&i.ListName,
		&i.DepartmentID,
		&i.DepartmentName,
		&i.TotalItems,
		&i.CreatedAt,
	)
	return i, err
}

const getListEntryById = `-- name: GetListEntryById :one
SELECT
	ld.list_entry_id,
	ld.list_id,
	ld.item_id,
	v.vendor_id,
	loc.location_id,
	ld.list_count,
	v.vendor_name,
	loc.location_name,
	i.upc,
	i.invoice_number,
	i.brand,
	i.name,
	i.description,
	i.price,
	i.weighed,
	COALESCE(i.count, 0) AS count,
	i.deleted
FROM list_data ld
JOIN lists lst ON ld.list_id = lst.list_id
JOIN inventory i ON ld.item_id = i.id
JOIN vendors v ON i.vendor_id = v.vendor_id
JOIN locations loc ON i.location_id = loc.location_id
WHERE ld.list_entry_id = $1
`

type GetListEntryByIdRow struct {
	ListEntryID   int32        `json:"list_entry_id"`
	ListID        int32        `json:"list_id"`
	ItemID        int32        `json:"item_id"`
	VendorID      int32        `json:"vendor_id"`
	LocationID    int32        `json:"location_id"`
	ListCount     int32        `json:"list_count"`
	VendorName    string       `json:"vendor_name"`
	LocationName  string       `json:"location_name"`
	Upc           string       `json:"upc"`
	InvoiceNumber string       `json:"invoice_number"`
	Brand         string       `json:"brand"`
	Name          string       `json:"name"`
	Description   string       `json:"description"`
	Price         float64      `json:"price"`
	Weighed       bool         `json:"weighed"`
	Count         int32        `json:"count"`
	Deleted       sql.NullBool `json:"deleted"`
}

func (q *Queries) GetListEntryById(ctx context.Context, listEntryID int32) (GetListEntryByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getListEntryById, listEntryID)
	var i GetListEntryByIdRow
	err := row.Scan(
		&i.ListEntryID,
		&i.ListID,
		&i.ItemID,
		&i.VendorID,
		&i.LocationID,
		&i.ListCount,
		&i.VendorName,
		&i.LocationName,
		&i.Upc,
		&i.InvoiceNumber,
		&i.Brand,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Weighed,
		&i.Count,
		&i.Deleted,
	)
	return i, err
}

const getListEntrys = `-- name: GetListEntrys :many
SELECT
	ld.list_entry_id,
	ld.list_id,
	ld.item_id,
	v.vendor_id,
	loc.location_id,
	ld.list_count,
	v.vendor_name,
	loc.location_name,
	i.upc,
	i.invoice_number,
	i.brand,
	i.name,
	i.description,
	i.price,
	i.weighed,
	COALESCE(ld.list_count, 0) AS count,
	i.deleted
FROM list_data ld
JOIN lists lst ON ld.list_id = lst.list_id
JOIN inventory i ON ld.item_id = i.id
JOIN vendors v ON i.vendor_id = v.vendor_id
JOIN locations loc ON i.location_id = loc.location_id
WHERE ld.list_id = $1
ORDER BY loc.location_name ASC, ld.list_entry_id DESC
`

type GetListEntrysRow struct {
	ListEntryID   int32        `json:"list_entry_id"`
	ListID        int32        `json:"list_id"`
	ItemID        int32        `json:"item_id"`
	VendorID      int32        `json:"vendor_id"`
	LocationID    int32        `json:"location_id"`
	ListCount     int32        `json:"list_count"`
	VendorName    string       `json:"vendor_name"`
	LocationName  string       `json:"location_name"`
	Upc           string       `json:"upc"`
	InvoiceNumber string       `json:"invoice_number"`
	Brand         string       `json:"brand"`
	Name          string       `json:"name"`
	Description   string       `json:"description"`
	Price         float64      `json:"price"`
	Weighed       bool         `json:"weighed"`
	Count         int32        `json:"count"`
	Deleted       sql.NullBool `json:"deleted"`
}

func (q *Queries) GetListEntrys(ctx context.Context, listID int32) ([]GetListEntrysRow, error) {
	rows, err := q.db.QueryContext(ctx, getListEntrys, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetListEntrysRow
	for rows.Next() {
		var i GetListEntrysRow
		if err := rows.Scan(
			&i.ListEntryID,
			&i.ListID,
			&i.ItemID,
			&i.VendorID,
			&i.LocationID,
			&i.ListCount,
			&i.VendorName,
			&i.LocationName,
			&i.Upc,
			&i.InvoiceNumber,
			&i.Brand,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Weighed,
			&i.Count,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLists = `-- name: GetLists :many
SELECT
	l.list_id,
	l.list_name,
	l.department_id,
	COALESCE(COUNT(ld.list_count), 0)::bigint AS total_items,
	l.created_at
FROM lists l
LEFT JOIN list_data ld ON l.list_id = ld.list_id
WHERE ($1::integer = 0 OR l.department_id = $1)
GROUP BY l.list_id, l.list_name, l.department_id, l.created_at
ORDER BY l.list_id DESC
`

type GetListsRow struct {
	ListID       int32     `json:"list_id"`
	ListName     string    `json:"list_name"`
	DepartmentID int32     `json:"department_id"`
	TotalItems   int64     `json:"total_items"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetLists(ctx context.Context, departmentID int32) ([]GetListsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLists, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetListsRow
	for rows.Next() {
		var i GetListsRow
		if err := rows.Scan(
			&i.ListID,
			&i.ListName,
			&i.DepartmentID,
			&i.TotalItems,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNumberOfItemsList = `-- name: GetNumberOfItemsList :one
SELECT COALESCE(SUM(list_count), 0)::bigint AS total_items
FROM list_data
WHERE list_id = $1
`

func (q *Queries) GetNumberOfItemsList(ctx context.Context, listID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNumberOfItemsList, listID)
	var total_items int64
	err := row.Scan(&total_items)
	return total_items, err
}

const updateEntryInList = `-- name: UpdateEntryInList :execrows
UPDATE list_data
	SET list_count = $1
	WHERE list_entry_id = $2
`

type UpdateEntryInListParams struct {
	ListCount   int32 `json:"list_count"`
	ListEntryID int32 `json:"list_entry_id"`
}

func (q *Queries) UpdateEntryInList(ctx context.Context, arg UpdateEntryInListParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEntryInList, arg.ListCount, arg.ListEntryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateList = `-- name: UpdateList :execrows
UPDATE lists
	SET list_name = $1
	WHERE list_id = $2
`

type UpdateListParams struct {
	ListName string `json:"list_name"`
	ListID   int32  `json:"list_id"`
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateList, arg.ListName, arg.ListID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
