// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package sqlcdb

import (
	"context"
)

const addLocation = `-- name: AddLocation :execrows
INSERT INTO locations (location_name)
	VALUES ($1)
`

func (q *Queries) AddLocation(ctx context.Context, locationName string) (int64, error) {
	result, err := q.db.ExecContext(ctx, addLocation, locationName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLocation = `-- name: DeleteLocation :execrows
DELETE FROM locations WHERE location_id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, locationID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLocation, locationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLocations = `-- name: GetLocations :many
SELECT  l.location_id,
        l.location_name,
        CAST((SELECT COALESCE(COUNT(i.id), 0)
	FROM inventory AS i
	WHERE i.location_id = l.location_id) AS INTEGER) AS total_items
	FROM locations AS l
	WHERE l.location_id != 1
	ORDER BY location_id DESC
`

type GetLocationsRow struct {
	LocationID   int32  `json:"location_id"`
	LocationName string `json:"location_name"`
	TotalItems   int32  `json:"total_items"`
}

func (q *Queries) GetLocations(ctx context.Context) ([]GetLocationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLocationsRow
	for rows.Next() {
		var i GetLocationsRow
		if err := rows.Scan(&i.LocationID, &i.LocationName, &i.TotalItems); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :execrows
UPDATE locations
    SET location_name = $1
	WHERE location_id = $2
`

type UpdateLocationParams struct {
	LocationName string `json:"location_name"`
	LocationID   int32  `json:"location_id"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLocation, arg.LocationName, arg.LocationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
