// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
	"time"
)

type Department struct {
	DepartmentID   int32  `json:"department_id"`
	DepartmentName string `json:"department_name"`
}

type Inventory struct {
	ID            int32         `json:"id"`
	VendorID      sql.NullInt32 `json:"vendor_id"`
	LocationID    sql.NullInt32 `json:"location_id"`
	DepartmentID  int32         `json:"department_id"`
	Upc           string        `json:"upc"`
	InvoiceNumber string        `json:"invoice_number"`
	Name          string        `json:"name"`
	Brand         string        `json:"brand"`
	Description   string        `json:"description"`
	Price         float64       `json:"price"`
	Weighed       bool          `json:"weighed"`
	Count         int32         `json:"count"`
	ArrivedAt     time.Time     `json:"arrived_at"`
	SoldoutAt     *time.Time    `json:"soldout_at"`
	Deleted       sql.NullBool  `json:"deleted"`
}

type Invoice struct {
	InvoiceID    int32     `json:"invoice_id"`
	InvoiceName  string    `json:"invoice_name"`
	InvoiceType  string    `json:"invoice_type"`
	DepartmentID int32     `json:"department_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type InvoiceDatum struct {
	InvoiceDataID int32   `json:"invoice_data_id"`
	InvoiceID     int32   `json:"invoice_id"`
	Rawtext       string  `json:"rawtext"`
	Upc           string  `json:"upc"`
	Details       string  `json:"details"`
	Qty           int32   `json:"qty"`
	ItemCost      float64 `json:"item_cost"`
	TotalCost     float64 `json:"total_cost"`
	DiscountCost  float64 `json:"discount_cost"`
	TrueCost      float64 `json:"true_cost"`
}

type List struct {
	ListID       int32     `json:"list_id"`
	ListName     string    `json:"list_name"`
	DepartmentID int32     `json:"department_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type ListDatum struct {
	ListEntryID int32 `json:"list_entry_id"`
	ListID      int32 `json:"list_id"`
	ItemID      int32 `json:"item_id"`
	ListCount   int32 `json:"list_count"`
}

type Location struct {
	LocationID   int32  `json:"location_id"`
	LocationName string `json:"location_name"`
}

type OcrFile struct {
	FileID        int32      `json:"file_id"`
	InvoiceID     int32      `json:"invoice_id"`
	Filepath      string     `json:"filepath"`
	Status        int32      `json:"status"`
	EntriesAdded  int32      `json:"entries_added"`
	EntriesFailed int32      `json:"entries_failed"`
	ErrorMessage  string     `json:"error_message"`
	StartedAt     *time.Time `json:"started_at"`
	CompletedAt   *time.Time `json:"completed_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

type Vendor struct {
	VendorID   int32  `json:"vendor_id"`
	VendorName string `json:"vendor_name"`
}
