// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ocr.sql

package sqlcdb

import (
	"context"
)

const createOCREntry = `-- name: CreateOCREntry :one
INSERT INTO ocr_files (invoice_id, filepath, status)
	VALUES ($1, $2, $3)
	RETURNING file_id
`

type CreateOCREntryParams struct {
	InvoiceID int32  `json:"invoice_id"`
	Filepath  string `json:"filepath"`
	Status    int32  `json:"status"`
}

func (q *Queries) CreateOCREntry(ctx context.Context, arg CreateOCREntryParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createOCREntry, arg.InvoiceID, arg.Filepath, arg.Status)
	var file_id int32
	err := row.Scan(&file_id)
	return file_id, err
}

const deleteOCREntryById = `-- name: DeleteOCREntryById :execrows
DELETE FROM ocr_files
WHERE file_id = $1 AND ($2::boolean = true OR status != 1)
`

type DeleteOCREntryByIdParams struct {
	FileID int32 `json:"file_id"`
	Force  bool  `json:"force"`
}

func (q *Queries) DeleteOCREntryById(ctx context.Context, arg DeleteOCREntryByIdParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOCREntryById, arg.FileID, arg.Force)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOCREntryById = `-- name: GetOCREntryById :one
SELECT
	file_id,
	invoice_id,
	filepath,
	status,
	entries_added,
	entries_failed,
	error_message,
	started_at,
	completed_at,
	created_at
FROM ocr_files
WHERE file_id = $1
`

func (q *Queries) GetOCREntryById(ctx context.Context, fileID int32) (OcrFile, error) {
	row := q.db.QueryRowContext(ctx, getOCREntryById, fileID)
	var i OcrFile
	err := row.Scan(
		&i.FileID,
		&i.InvoiceID,
		&i.Filepath,
		&i.Status,
		&i.EntriesAdded,
		&i.EntriesFailed,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOCREntrysByInvoiceID = `-- name: GetOCREntrysByInvoiceID :many
SELECT
	file_id,
	invoice_id,
	filepath,
	status,
	entries_added,
	entries_failed,
	error_message,
	started_at,
	completed_at,
	created_at
FROM ocr_files
WHERE invoice_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOCREntrysByInvoiceID(ctx context.Context, invoiceID int32) ([]OcrFile, error) {
	rows, err := q.db.QueryContext(ctx, getOCREntrysByInvoiceID, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OcrFile
	for rows.Next() {
		var i OcrFile
		if err := rows.Scan(
			&i.FileID,
			&i.InvoiceID,
			&i.Filepath,
			&i.Status,
			&i.EntriesAdded,
			&i.EntriesFailed,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnfinishedEntrys = `-- name: GetUnfinishedEntrys :many
SELECT
	file_id,
	invoice_id,
	filepath,
	status,
	entries_added,
	entries_failed,
	error_message,
	started_at,
	completed_at,
	created_at
FROM ocr_files
WHERE status IN ($1, $2)
`

type GetUnfinishedEntrysParams struct {
	Status   int32 `json:"status"`
	Status_2 int32 `json:"status_2"`
}

func (q *Queries) GetUnfinishedEntrys(ctx context.Context, arg GetUnfinishedEntrysParams) ([]OcrFile, error) {
	rows, err := q.db.QueryContext(ctx, getUnfinishedEntrys, arg.Status, arg.Status_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OcrFile
	for rows.Next() {
		var i OcrFile
		if err := rows.Scan(
			&i.FileID,
			&i.InvoiceID,
			&i.Filepath,
			&i.Status,
			&i.EntriesAdded,
			&i.EntriesFailed,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAsFinished = `-- name: MarkAsFinished :execrows
UPDATE ocr_files
	SET status = $1, entries_added = $2, entries_failed = $3, error_message = $4, completed_at = CURRENT_TIMESTAMP
	WHERE file_id = $5
`

type MarkAsFinishedParams struct {
	Status        int32  `json:"status"`
	EntriesAdded  int32  `json:"entries_added"`
	EntriesFailed int32  `json:"entries_failed"`
	ErrorMessage  string `json:"error_message"`
	FileID        int32  `json:"file_id"`
}

func (q *Queries) MarkAsFinished(ctx context.Context, arg MarkAsFinishedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAsFinished,
		arg.Status,
		arg.EntriesAdded,
		arg.EntriesFailed,
		arg.ErrorMessage,
		arg.FileID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markAsProccessing = `-- name: MarkAsProccessing :execrows
UPDATE ocr_files
	SET status = $1, started_at = CURRENT_TIMESTAMP
	WHERE file_id = $2
`

type MarkAsProccessingParams struct {
	Status int32 `json:"status"`
	FileID int32 `json:"file_id"`
}

func (q *Queries) MarkAsProccessing(ctx context.Context, arg MarkAsProccessingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAsProccessing, arg.Status, arg.FileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
