// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const searchInvoice = `-- name: SearchInvoice :many
SELECT
	id.invoice_data_id,
	id.invoice_id,
	id.rawtext,
	id.upc,
	id.details,
	id.qty,
	id.item_cost,
	id.total_cost,
	id.discount_cost,
	id.true_cost,
	COUNT(*) OVER() AS total_items
FROM invoice_data id
WHERE
	invoice_id = $1 AND (
		LOWER(id.rawtext) LIKE $2
		OR LOWER(id.upc) LIKE $2
		OR LOWER(id.details) LIKE $2
	)
ORDER BY id.qty DESC
LIMIT $3 OFFSET $4
`

type SearchInvoiceParams struct {
	InvoiceID int32  `json:"invoice_id"`
	Rawtext   string `json:"rawtext"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type SearchInvoiceRow struct {
	InvoiceDataID int32   `json:"invoice_data_id"`
	InvoiceID     int32   `json:"invoice_id"`
	Rawtext       string  `json:"rawtext"`
	Upc           string  `json:"upc"`
	Details       string  `json:"details"`
	Qty           int32   `json:"qty"`
	ItemCost      float64 `json:"item_cost"`
	TotalCost     float64 `json:"total_cost"`
	DiscountCost  float64 `json:"discount_cost"`
	TrueCost      float64 `json:"true_cost"`
	TotalItems    int64   `json:"total_items"`
}

func (q *Queries) SearchInvoice(ctx context.Context, arg SearchInvoiceParams) ([]SearchInvoiceRow, error) {
	rows, err := q.db.QueryContext(ctx, searchInvoice,
		arg.InvoiceID,
		arg.Rawtext,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchInvoiceRow
	for rows.Next() {
		var i SearchInvoiceRow
		if err := rows.Scan(
			&i.InvoiceDataID,
			&i.InvoiceID,
			&i.Rawtext,
			&i.Upc,
			&i.Details,
			&i.Qty,
			&i.ItemCost,
			&i.TotalCost,
			&i.DiscountCost,
			&i.TrueCost,
			&i.TotalItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItems = `-- name: SearchItems :many
SELECT
	i.id,
	v.vendor_id,
	v.vendor_name,
	l.location_id,
	l.location_name,
	i.upc,
	i.invoice_number,
	i.brand,
	i.name,
	i.description,
	i.price,
	i.weighed,
	COALESCE(i.count, 0) AS count,
	i.deleted,
	i.arrived_at,
	i.soldout_at,
	COALESCE(ld.list_entry_id, -1) AS list_entry_id,
	COALESCE(ld.list_count, -1) AS list_count,
	COUNT(*) OVER() AS entry_count
FROM inventory i
JOIN vendors v ON i.vendor_id = v.vendor_id
JOIN locations l ON l.location_id = i.location_id
LEFT JOIN list_data ld ON i.id = ld.item_id AND ld.list_id = $1
WHERE
	(LOWER(i.name) LIKE $2
	 OR LOWER(i.brand) LIKE $2
	 OR LOWER(i.description) LIKE $2
	 OR LOWER(v.vendor_name) LIKE $2
	 OR LOWER(i.upc) LIKE $2
	 OR LOWER(i.invoice_number) LIKE $2)
	AND ($3::boolean = true OR i.deleted = false)
	AND ($4::integer = 0 OR i.vendor_id = $4)
	AND ($5::integer = 0 OR i.location_id = $5)
	AND ($6::integer = 0 OR i.department_id = $6)
	AND ($7::boolean = false OR ld.list_id = $1)
ORDER BY CASE $8::text
	WHEN 'date' THEN CAST(i.arrived_at AS TEXT)
	WHEN 'name' THEN i.name
	ELSE i.upc
END DESC
LIMIT $10 OFFSET $9
`

type SearchItemsParams struct {
	ListID      int32  `json:"list_id"`
	Search      string `json:"search"`
	ShowDeleted bool   `json:"show_deleted"`
	Vendor      int32  `json:"vendor"`
	Location    int32  `json:"location"`
	Department  int32  `json:"department"`
	LimitToList bool   `json:"limit_to_list"`
	OrderBy     string `json:"order_by"`
	PageOffset  int32  `json:"page_offset"`
	PageSize    int32  `json:"page_size"`
}

type SearchItemsRow struct {
	ID            int32        `json:"id"`
	VendorID      int32        `json:"vendor_id"`
	VendorName    string       `json:"vendor_name"`
	LocationID    int32        `json:"location_id"`
	LocationName  string       `json:"location_name"`
	Upc           string       `json:"upc"`
	InvoiceNumber string       `json:"invoice_number"`
	Brand         string       `json:"brand"`
	Name          string       `json:"name"`
	Description   string       `json:"description"`
	Price         float64      `json:"price"`
	Weighed       bool         `json:"weighed"`
	Count         int32        `json:"count"`
	Deleted       sql.NullBool `json:"deleted"`
	ArrivedAt     time.Time    `json:"arrived_at"`
	SoldoutAt     *time.Time   `json:"soldout_at"`
	ListEntryID   int32        `json:"list_entry_id"`
	ListCount     int32        `json:"list_count"`
	EntryCount    int64        `json:"entry_count"`
}

func (q *Queries) SearchItems(ctx context.Context, arg SearchItemsParams) ([]SearchItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchItems,
		arg.ListID,
		arg.Search,
		arg.ShowDeleted,
		arg.Vendor,
		arg.Location,
		arg.Department,
		arg.LimitToList,
		arg.OrderBy,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchItemsRow
	for rows.Next() {
		var i SearchItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.VendorName,
			&i.LocationID,
			&i.LocationName,
			&i.Upc,
			&i.InvoiceNumber,
			&i.Brand,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Weighed,
			&i.Count,
			&i.Deleted,
			&i.ArrivedAt,
			&i.SoldoutAt,
			&i.ListEntryID,
			&i.ListCount,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
