// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vendors.sql

package sqlcdb

import (
	"context"
)

const addVendor = `-- name: AddVendor :execrows
INSERT INTO vendors (vendor_name)
	VALUES ($1)
`

func (q *Queries) AddVendor(ctx context.Context, vendorName string) (int64, error) {
	result, err := q.db.ExecContext(ctx, addVendor, vendorName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteVendor = `-- name: DeleteVendor :execrows
DELETE FROM vendors WHERE vendor_id = $1
`

func (q *Queries) DeleteVendor(ctx context.Context, vendorID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVendor, vendorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getVendors = `-- name: GetVendors :many
SELECT  v.vendor_id,
        v.vendor_name,
        CAST((SELECT COALESCE(COUNT(i.id), 0)
	FROM inventory AS i
	WHERE i.vendor_id = v.vendor_id) AS INTEGER) AS total_items
	FROM vendors AS v
	WHERE vendor_id != 1
	ORDER BY vendor_id DESC
`

type GetVendorsRow struct {
	VendorID   int32  `json:"vendor_id"`
	VendorName string `json:"vendor_name"`
	TotalItems int32  `json:"total_items"`
}

func (q *Queries) GetVendors(ctx context.Context) ([]GetVendorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getVendors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVendorsRow
	for rows.Next() {
		var i GetVendorsRow
		if err := rows.Scan(&i.VendorID, &i.VendorName, &i.TotalItems); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendor = `-- name: UpdateVendor :execrows
UPDATE vendors
    SET vendor_name = $1
	WHERE vendor_id = $2
`

type UpdateVendorParams struct {
	VendorName string `json:"vendor_name"`
	VendorID   int32  `json:"vendor_id"`
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVendor, arg.VendorName, arg.VendorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
